"""Producer-compatibility proof — the scorecard parses matrices GENERATED by
the create-matrix engine (the falke-bid-tools plugin), at a VARIABLE number
of bidders.

The committed fixtures (tests/fixtures/create_matrix_{2,4}bidders.xlsx) are
REAL output of the producer's own writer + normalize pipeline
(plugin/falke-bid-tools/engines/matrix/src/write_matrix.py), built from FULLY
SYNTHETIC bids — fictional firms, fictional dollars, no client data. They are
regenerated only by tests/fixtures/_make_create_matrix_fixtures.py, so this
suite never imports the producer.

Producer geometry differs from the reference layout the parser was built
against, in exactly the ways these tests pin down:
  * sub-header row ABOVE the bidder names (headers row 4, names row 5) —
    inverted vs the reference layout (names row 8, quartet row 12);
  * Bid_Form groups are 2 labeled columns (COST SUBTOTALS | $/GSF), stride 3
    — no plain COST column, and the $/SF header carries the per-run SF-basis
    label ("$/GSF"), not literal "$/SF";
  * no "TOTAL GSF" labeled row — the SF basis lives in the row-2 details
    line ("... | 12,000 GSF");
  * Bid_Form footer says "GRAND TOTAL" (machine key in col A), not
    "GRAND TOTAL CONSTRUCTION COST" — the safe below-markup fallback applies;
  * Leveled_Normalized keeps the FEB 26 4-column groups (stride 5) with the
    exact "GRAND TOTAL CONSTRUCTION COST" label.

The sample gold suite (test_integration_sample.py) proves the reference
orientation still parses identically.
"""
from __future__ import annotations

import os

import pytest

from scorecard.config import load_config
from scorecard.matrix import MatrixParser
from scorecard.pipeline import run_scorecard

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures")

# The producer fixtures are gitignored synthetic binaries (regenerate with
# tests/fixtures/_make_create_matrix_fixtures.py). Present in the working tree /
# CI; a fresh clone that hasn't regenerated them skips this suite rather than
# erroring — mirrors the absent-binary skip pattern the integration suite uses.
pytestmark = pytest.mark.skipif(
    not (os.path.exists(os.path.join(FIXTURES, "create_matrix_2bidders.xlsx"))
         and os.path.exists(os.path.join(FIXTURES, "create_matrix_4bidders.xlsx"))),
    reason="create-matrix producer fixtures absent (gitignored binaries; "
           "regenerate with tests/fixtures/_make_create_matrix_fixtures.py)")

# synthetic grand totals written by _make_create_matrix_fixtures.py
# (base divisions 250k+400k+300k+150k = 1.10M, scaled by 1 + 0.08*i)
FIXTURE_FIELDS = {
    2: {
        "Alpine Restoration Group": 1_100_000.0,
        "Bayside Builders LLC": 1_188_000.0,
    },
    4: {
        "Alpine Restoration Group": 1_100_000.0,
        "Bayside Builders LLC": 1_188_000.0,
        "Cypress Construction Co.": 1_276_000.0,
        "Driftwood Contractors": 1_364_000.0,
    },
}
FIXTURE_GSF = 12_000.0   # written into the row-2 details line ("12,000 GSF")


def _fixture(n: int) -> str:
    return os.path.join(FIXTURES, f"create_matrix_{n}bidders.xlsx")


def _matrix_cfg():
    """The SHIPPED matrix block — no producer-specific knobs."""
    return load_config(overrides={
        "sf_basis": 10_000,
        "band_low": 1.00,
        "band_high": 1.20,
        "modeled_mid_takeoff": 1.10,
    })


@pytest.mark.parametrize("n_bidders", [2, 4])
def test_parses_create_matrix_bid_form_at_variable_bidder_counts(n_bidders):
    """Same shipped config, different bidder counts: every block detected,
    every grand total read, nothing dropped or flagged."""
    parsed = MatrixParser(_matrix_cfg().block("matrix")).parse(_fixture(n_bidders))

    # default sheet resolution = first sheet = the producer's Bid_Form mirror
    assert parsed.sheet_name == "Bid_Form"

    # bidder-column detection: the field size is MEASURED, not assumed
    expected = FIXTURE_FIELDS[n_bidders]
    assert len(parsed.blocks) == n_bidders, [b.raw_name for b in parsed.blocks]
    assert len(parsed.included_blocks) == n_bidders
    # producer Bid_Form geometry: 2 labeled cols per group, names 3 apart
    assert parsed.block_stride == 3
    assert parsed.block_width == 2

    by_name = {b.raw_name: b for b in parsed.included_blocks}
    assert set(by_name) == set(expected)
    for name, total in expected.items():
        assert by_name[name].grand_total == total, name

    # grand total via the safe fallback (lowest total BELOW the pre-markup
    # construction subtotal) — never the CONSTRUCTION COST SUBTOTAL itself
    assert parsed.grand_total_label.upper().startswith("GRAND TOTAL")
    assert parsed.construction_subtotal_row is not None
    assert parsed.grand_total_row > parsed.construction_subtotal_row

    # GSF detected from the details line — reported only (Marvin §3)
    assert parsed.gsf_value == FIXTURE_GSF

    # every bidder populates the same 4 priced CSI divisions -> no
    # completeness outliers, no duplicates
    for b in parsed.included_blocks:
        assert b.populated_divisions == 4, (b.raw_name, b.populated_divisions)
        assert b.flags == [], b.flags
        assert b.drop_reason is None


def test_detect_sf_suggests_details_line_gsf():
    """The CLI's suggest-and-confirm SF gate gets a suggestion from producer
    output even though there is no 'TOTAL GSF' labeled row."""
    parser = MatrixParser(_matrix_cfg().block("matrix"))
    gsf_row, gsf_val = parser.detect_sf(_fixture(4))
    assert gsf_val == FIXTURE_GSF
    assert gsf_row == 2   # the producer's details line


def test_bidder_count_is_flexible_not_fixture_shaped():
    """One parser instance, same config, both fixtures: the detected field
    tracks each workbook's own bidder count."""
    parser = MatrixParser(_matrix_cfg().block("matrix"))
    counts = {n: len(parser.parse(_fixture(n)).included_blocks) for n in (2, 4)}
    assert counts == {2: 2, 4: 4}


def test_leveled_normalized_sheet_also_parses_with_matching_totals():
    """The producer's Leveled_Normalized sheet (FEB 26 4-col groups, stride 5,
    exact grand-total label) parses via sheet_name override, and its grand
    totals equal the Bid_Form mirror's (the producer's tie-out invariant)."""
    cfg = _matrix_cfg().block("matrix")
    mirror = MatrixParser(cfg).parse(_fixture(4))

    cfg_lev = dict(cfg)
    cfg_lev["sheet_name"] = "Leveled_Normalized"
    leveled = MatrixParser(cfg_lev).parse(_fixture(4))

    assert leveled.sheet_name == "Leveled_Normalized"
    assert len(leveled.included_blocks) == 4
    assert leveled.block_stride == 5
    assert leveled.block_width == 4
    assert leveled.grand_total_label.strip().upper() == \
        "GRAND TOTAL CONSTRUCTION COST"

    mirror_totals = {b.raw_name: b.grand_total for b in mirror.included_blocks}
    leveled_totals = {b.raw_name: b.grand_total for b in leveled.included_blocks}
    assert leveled_totals == mirror_totals


def test_pipeline_end_to_end_on_create_matrix_output():
    """Full scorecard pipeline on producer output: $/SF on the SUPPLIED basis
    (10,000 — NOT the matrix's 12,000), all bidders tiered and ranked."""
    cfg = _matrix_cfg()
    result = run_scorecard(_fixture(4), cfg,
                           project_name="Harborview Synthetic Test Tower")
    by_name = {b["name"]: b for b in result["bidders"]}
    assert set(by_name) == set(FIXTURE_FIELDS[4])

    for name, total in FIXTURE_FIELDS[4].items():
        assert by_name[name]["per_sf"] == round(total / 10_000), name
    # prove the matrix GSF (12,000) was NOT the denominator
    assert by_name["Alpine Restoration Group"]["per_sf"] == 110
    assert round(1_100_000 / FIXTURE_GSF) != 110

    ranks = sorted(b["rank"] for b in result["bidders"])
    assert ranks == [1, 2, 3, 4]
    assert len(result["ranking"]) == 4
